DROP TABLE LOGIN;
CREATE TABLE LOGIN (
    NO NUMBER,
    ID VARCHAR2(100),
    PW VARCHAR2(100),
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(100),
    JOIN_DATE DATE,
    STATE NUMBER(10)
);
DROP SEQUENCE LOGIN_SEQ;
CREATE SEQUENCE LOGIN_SEQ;

INSERT INTO LOGIN VALUES (LOGIN_SEQ.NEXTVAL, 'AAA', 'AAA', 'AAA', 'AAAAAA123@naver.com', '010-1111-1111', SYSDATE, 1 );

COMMIT;
