drop table board;
CREATE TABLE board
(
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(100),
    CREATED DATE,
    LASTMODIFIED DATE
);
DROP SEQUENCE board_SEQ;
CREATE SEQUENCE board_SEQ NOCACHE;

INSERT INTO board VALUES (board_SEQ.NEXTVAL, '111', '111', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '222', '222', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '333', '333', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '444', '444', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '555', '555', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '666', '666', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '777', '777', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '888', '888', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '999', '999', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1010', '1010', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1111', '1111', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1212', '1212', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1313', '1313', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1414', '1414', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1515', '1515', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1616', '1616', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1717', '1717', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1818', '1818', SYSDATE, SYSDATE);
INSERT INTO board VALUES (board_SEQ.NEXTVAL, '1919', '1919', SYSDATE, SYSDATE);


COMMIT;
